### ISSUE TITLE
Initial value not displaying with TimePicker widget

### ISSUE THREAD

**Issue by knasti** [FlipperPA/django-tempus-dominus#50] opened 2019-04-30 12:31 UTC
Hi again,

I have had some difficulties using the TimePicker for update views (UpdateView), as I can't get it to display the initial value of the object to be updated, see the pictures below. As the pictures show, I have had no issues with DateTimePicker and its initial value (no issues with the DatePicker either).

### Picture with TimePicker:
![image](https://user-images.githubusercontent.com/21027620/56960698-fcd74480-6b51-11e9-8f05-412caf36c3ab.png)

### Picture without TimePicker:
![image](https://user-images.githubusercontent.com/21027620/56960772-33ad5a80-6b52-11e9-86a1-eb2c7a583698.png)

My widget looks as follows:
```
class TaskUpdateForm(forms.ModelForm):
    class Meta:
        ...
        widgets = {
            "start_time": TimePicker(
                options={"format": "HH:mm:ss"},
                attrs={
                    "append": "far fa-clock",
                    "input_toggle": False,
                    "icon_toggle": True,
                },
            ),
        }
```

Can you tell, based on this information, whether this issue is on my or your end, and if so suggest what can be done to solve it?

I hope you can help.

Best regards,
Niels

**Comment by FlipperPA** [comment] 2019-05-13 13:52
@knasti I doubt this is the issue (which I'll look into), but for the missing icon, change `far fa-clock` to `fa fa-clock`.

**Comment by FlipperPA** [comment] 2019-05-14 13:29
@knasti Unfortunately, after doing some digging, this seems to be a problem with the underlying Tempus Dominus JavaScript library. For now, I've updated the README to show how you can set the default time in the TimePicker:

`'defaultDate': '1970-01-01T14:56:00'`

But I haven't been able to figure out a way to get it to populate `initial`. I'll keep digging, but for now, I hope this helps.

**Comment by geojsg** [comment] 2019-05-17 09:15
I am also experiencing same issue. 
With a model form, at update (instanced form), the field value is not populated with data from database except if initialized with the datetime picker.
Any progress to solve this critical issue ?

**Comment by billlhead** [comment] 2019-05-17 14:59
I've tried setting that defaultDate and the correct time is shown when I toggle the control but there's no way to accept that defaultDate as the selected time, you have to change the selected time to get it to show up in the input control.

Any way around that or setting it by javascript for now? I've tried setting the value of the input box manually on page load but the time only flashes and then it quickly goes blank again.

**Comment by serranomorante** [comment] 2019-07-09 04:00
The following approach worked for me. I had to customize the "script" portion of the generated html form, just replacing the "date" value with a django filter tag showing a _date part_ (you could put any date), and a _time part_ (the time from your database), separated by a "T" letter, which will render to this: "2019-07-08T22:34:50".
Hope it helps.

````html        
<div class="form-group col-md-2">
            {{ form.hora_cita.errors }}
            {{ form.hora_cita.label_tag }}
            <div class="input-group" id="div_{{ form.hora_cita.id_for_label }}" data-target-input="nearest">
                <input type="text" name="{{ form.hora_cita.html_name }}"
                required id="{{ form.hora_cita.id_for_label }}" class="form-control datetimepicker-input"
                data-toggle="datetimepicker" data-target="#{{ form.hora_cita.id_for_label }}">

            </div>
            <script type="text/javascript">
                $(function () {
                    $('#{{ form.hora_cita.id_for_label }}').datetimepicker({"format": "HH:mm:ss", "icons": {"time": "fa fa-clock-o"},
                                                                            "date": "{{ object.fecha_inicial|date:'Y-m-d' }}T{{ object.hora_cita|date:'H:i:s' }}"});
                });
            </script>
        </div>```

**Comment by FlipperPA** [comment] 2019-08-16 18:23
Rather than putting in work-arounds for the `TimePicker` only, when `initial` works for all other fields, I'm going to wait and hope this gets fixed in the underlying library.

**Comment by milionlu** [comment] 2019-09-22 12:39
Hi,
I have the same issue.

I store a TimeField in the database and I try to display it with the TimePicker.
Everything works fine for the creation but the update does not work.

Fields are not pre-filled with the stored value and I get a moment warning:
`value provided is not in a recognized RFC2822 or ISO format`

Indeed, the generated script contains a wrong formatted date:
```
function deferDateTimePicker_id_start_time() {
    if (window.jQuery && $.fn.datetimepicker) {
        $('#id_start_time').datetimepicker({
                                       "format": "HH:mm",
                                       "icons": {"time": "fa fa-clock-o"},
                                       "useCurrent": true,
                                       "stepping": 5,
                                       "date": "T11:30:00"
                                      });
    } else {
        setTimeout(function() { deferDateTimePicker() }, 50);
    }
}
```
Do you have any idea how to fix it?
If you want, I can put a small test example on my github to reproduce.

**Comment by waltersdmh** [comment] 2019-11-04 10:58
I had to get this 'working' so did the following:

1. In my Update View, get the submitted Time from the request data or load it from DB.
2. Pass this value as a context variable.
3. Use JS to push the value into the input field.

View
```
def updateRequest(request):
    template_name = 'update/request.html'
    context = {}
    if request.method == 'POST':
        form = updateRequestForm(request.POST)

        if form.is_valid():
            pass  # does nothing, just trigger the validation
        
        context['start_time_initial'] = form['start_time'].value()

    context['form'] = form
    return render(request, template_name, context)
```

HTML
`document.getElementById("id_start_time").value = '{{start_time_initial}}';
`

My form field, if this matters
```
    start_time = forms.TimeField(
        required = True,
        widget=TimePicker(
            options={
            'useCurrent': True,
            'format':'HH:mm:ss',
            'defaultDate': '1970-01-01T14:56:00',
            },
            attrs={
                 'icon_toggle': True,
                 'autocomplete':"disabled",
                'append': 'fa fa-clock',

            },
        ),)
```

Will keep an eye out for a proper fix.

**Closed** 2020-01-18 13:18 UTC
Labels: bug, help wanted, possible-td-bug
