### ISSUE TITLE
TimePicker is showing full date

### ISSUE THREAD

**Issue by nhill-cpi** [FlipperPA/django-tempus-dominus#53] opened 2019-05-29 16:05 UTC
For one of my forms, two fields are time fields, and so I have the following in `forms.py`.

` 
        class Meta:
        model = DepotParameters
        fields = '__all__'

        widgets = {
            'window_start_time': TimePicker(
                options={
                    'collapse': True,
                    'keepInvalid': True
                }
            ),
            'window_end_time': TimePicker(
                options={
                    'collapse': True,
                    'keepInvalid': True,
                },
                attrs={'timepicker': True}
            )
        }
`.

However, when I'm rendering these fields in the HTML with `{{ form.window_start_time}}` and `{{ form.window_end_time}}`, the entire date is showing as the default value. Why isn't just the time displaying?

**Comment by nlittlejohns** [comment] 2019-07-16 14:03
@nhill-cpi did you find the solution to this? I'm having the same issue.

**Comment by FlipperPA** [comment] 2019-07-17 10:58
We're hoping to take a more in-depth look at this, but if anyone has ideas, we're all ears. From what I've seen so far it may be an issue with the underlying JS library.

**Comment by nhill-cpi** [comment] 2019-07-17 16:28
I believe I fixed this by changing my jQuery version.

**Comment by larsn7** [comment] 2019-07-20 17:13
It's not due to setting up your project wrong. In my honest (and little harsh opinion) it's bad design of Django-Tempus-Dominus.

When loading jQuery at the end of your page you'll optimize load times, but if we take a look at the widget.html file in TempusDominus we see this:
https://github.com/FlipperPA/django-tempus-dominus/blob/96d83ebc319f686b6a06db0670617a31fa790ec1/tempus_dominus/templates/tempus_dominus/widget.html#L18-L22

It's calling the jQuery shorthand for `$(document).ready(function() {...})`, that's fine you might think.

Well, actually no. The projects that think of optimizing their page loading place the jQuery file at the bottom of the page. But the Date/Time picker is never below that. That'll completely destroy the purpose of placing jQuery at the bottom of the page. So what happens is, the moment you load the page an error occurs in the console.
`Uncaught ReferenceError: $ is not defined`

Why does this happen? Simple, jQuery isn't included in the page yet (since you're optimizing load times by placing jQuery at the bottom of the page) but the JavaScript in the widget file is asking the same jQuery to wait for the document to be ready.

More proof that this is the problem:
Replacing the widget script part with this, it's basically waiting for jQuery and datetimepicker to actually exist and be loaded until creating the DateTimePicker.
```
console.log('DateTimePicker Precall')
function deferDateTimePicker() {
      if (window.jQuery && $.fn.datetimepicker) {
          console.log('Creating datetimepicker input')
          $('#{{ picker_id }}').datetimepicker({{ js_options }});
      }
    else
        setTimeout(function() { deferDateTimePicker() }, 50);
    }
    deferDateTimePicker()
```

If you open the console now, whilst loading the page you'll see no error but instead first the DateTimePicker Precall and a Creating datetimepicker input after that. Your input should work as intended (A timepicker only showing time, A datepicker only showing date).

Different proof:
Placing your `<script />` call for the jQuery in your `<head />` also results in the correct working for the input.

### **That's identifying the problem NOT a solution**
Since the first proof is just really messy and more of a practical test and the second proof ruining page load times, we need a better solution. But what?

For project creators, just wait until there's a solution merged into the main branch and update the library. There's nothing what you really can do, except maybe temporarily giving up page load times. Don't start editing the source file as I did to give proof, when you deploy your project this will of course break.

For Django-Tempus-Dominus creators, I'd recommend somehow being able to place the function that eventually creates the element
https://github.com/FlipperPA/django-tempus-dominus/blob/96d83ebc319f686b6a06db0670617a31fa790ec1/tempus_dominus/templates/tempus_dominus/widget.html#L18-L22
in a separate JavaScript file and adding it to the media. This way, the users of the project can include it with `{{ form.media.js }}`

**Comment by FlipperPA** [comment] 2019-08-14 17:40
@larsn7 Thanks for the detective work and explanation. Unfortunately, I don't see a good and obvious way of dynamically providing the JS asset within the context of a Django widget. `{{ form.media }}` is rendered from a list of JS & CSS URLs by Django, and I don't see a way to override the `render` method from within the widget class. This would've allowed us to potentially tack on the necessary Javascript at the end.

For the meantime, I'm going to put the defer function into place, as it'll help in some situations.

**Closed** 2023-12-16 02:24 UTC
